version: '3.8'

services:
  app:
    build:
      context: ./user-api
      dockerfile: Dockerfile
    container_name: user-api
    ports:
      - "8080:8080"
    env_file:
      - ./secure-submodule/env/compose-local.env
    restart: always
    networks:
      - laundreader

networks:
  laundreader:
    driver: bridge