spring:
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        hbm2ddl.auto: create
  flyway:
    enabled: false
server:
  port: 8080