spring:
  application:
    name: user-api
  config:
    import: env.yml
  profiles:
    active: local
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST}
      port: ${SPRING_DATA_REDIS_PORT}
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}


management:
  endpoints:
    web:
      base-path: /actuator

server:
  address: 0.0.0.0