management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
        exclude: env, loggers, heapdump, threaddump
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: user-api
  prometheus:
    enabled: true

redis:
  host: localhost
  port: 6379

datasource:
  url: jdbc:mysql://localhost:3307/test_db
  username: test_user
  password: test_pass
jpa:
  hibernate:
    ddl-auto: update
  properties:
    hibernate:
      format_sql: true
      show_sql: true

server:
  port: 8080