-- V1__init.sql
-- 초기 스키마 정의

CREATE TABLE user_tb (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(60) NOT NULL,
    provider VARCHAR(10) NOT NULL,
    role VARCHAR(10) NOT NULL DEFAULT 'USER',
    nick_name VARCHAR(30) NOT NULL,
    status VARCHAR(10) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
